easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Language
        - App\Entity\City
        - App\Entity\Participant
        - App\Entity\Event
